export const allPagesContent = [
    { id: 1, title: "Search Results Page", description: "Content from Search Results Page.", category: "Page", url: "/search" },
    { id: 2, title: "Events", description: "Content from Events page.", category: "Page", url: "/events/list/" },
    { id: 3, title: "Reviews Page", description: "Content from Reviews Page.", category: "Page", url: "/reviews/page/" },
    { id: 4, title: "About Page", description: "Content from About Page.", category: "Page", url: "/about" },
    { id: 5, title: "Accreditation Page", description: "Content from Accreditation Page.", category: "Page", url: "/Accreditation/" },
    { id: 6, title: "Admission Requirements Page", description: "Content from Admission Requirements Page.", category: "Page", url: "/admissions-requirements" },
    { id: 7, title: "Admissions Page", description: "Content from Admissions Page.", category: "Page", url: "/admissions" },
    { id: 8, title: "Affiliations Page", description: "Content from Affiliations Page.", category: "Page", url: "/affiliations/" },
    { id: 9, title: "Alumni", description: "Content from Alumni page.", category: "Page", url: "/alumni" },
    { id: 10, title: "Application Deadlines Page", description: "Content from Application Deadlines Page.", category: "Page", url: "/important-dates/" },
    { id: 11, title: "Apply JIU Page", description: "Content from Apply JIU Page.", category: "Page", url: "/apply-now/" },
    { id: 12, title: "Blog", description: "Content from Blog page.", category: "Page", url: "/blog/" },
    { id: 13, title: "Board Of Directors Page", description: "Content from Board Of Directors Page.", category: "Page", url: "/who-we-are/leadership/board-of-directors/" },
    { id: 14, title: "Cabinet Page", description: "Content from Cabinet Page.", category: "Page", url: "/cabinet/" },
    { id: 15, title: "Career And Alumni Services", description: "Content from Career And Alumni Services page.", category: "Page", url: "/career-and-alumni-services/" },
    { id: 16, title: "Contact Us", description: "Content from Contact Us page.", category: "Page", url: "/contact_us" },
    { id: 17, title: "Dates Tuition Page", description: "Content from Dates Tuition Page.", category: "Page", url: "/dates-tuition/" },
    { id: 18, title: "Degree Programs Page", description: "Content from Degree Programs Page.", category: "Page", url: "/Degree-Programs/" },
    { id: 19, title: "Faculty Directory Page", description: "Content from Faculty Directory Page.", category: "Page", url: "/faculty-directory/" },
    { id: 20, title: "Faq Page", description: "Content from Faq Page.", category: "Page", url: "/Faq" },
    { id: 21, title: "History Page", description: "Content from History Page.", category: "Page", url: "/JIU-history/" },
    { id: 22, title: "Home Page", description: "Content from Home Page.", category: "Page", url: "*" },
    { id: 23, title: "International Students Page", description: "Content from International Students Page.", category: "Page", url: "/admissions/international-students/" },
    { id: 24, title: "JIU News Page", description: "Content from JIU News Page.", category: "Page", url: "/JIU-in-the-news/" },
    { id: 25, title: "Jobs At JIU Page", description: "Content from Jobs At JIU Page.", category: "Page", url: "/jobs-at-nyfa/" },
    { id: 26, title: "Leadership At JIU Page", description: "Content from Leadership At JIU Page.", category: "Page", url: "/who-we-are/leadership/" },
    { id: 27, title: "Membership Page", description: "Content from Membership Page.", category: "Page", url: "/JIU-membership/" },
    { id: 28, title: "Military Dependent Students Page", description: "Content from Military Dependent Students Page.", category: "Page", url: "/admissions/veterans-military-dependent-students/" },
    { id: 29, title: "Mission And Purpose Page", description: "Content from Mission And Purpose Page.", category: "Page", url: "/mission-and-purpose/" },
    { id: 30, title: "NYFA Student Life Page", description: "Content from NYFA Student Life Page.", category: "Page", url: "/student-life/" },
    { id: 31, title: "Online Programes", description: "Content from Online Programes page.", category: "Page", url: "/online-programs/" },
    { id: 32, title: "President Page", description: "Content from President Page.", category: "Page", url: "/presidents-page/" },
    { id: 33, title: "Privacy Policy Page", description: "Content from Privacy Policy Page.", category: "Page", url: "/policy/" },
    { id: 34, title: "Programfinder Page", description: "Content from Programfinder Page.", category: "Page", url: "/programfinder/" },
    { id: 35, title: "Request Info Page", description: "Content from Request Info Page.", category: "Page", url: "/request-info/" },
    { id: 36, title: "Scholarship And Grants Page", description: "Content from Scholarship And Grants Page.", category: "Page", url: "/ScholarshipAndGrants_page/" },
    { id: 37, title: "Student Resource Page", description: "Content from Student Resource Page.", category: "Page", url: "/current-student-resources/" },
    { id: 38, title: "Student Resources", description: "Content from Student Resources page.", category: "Page", url: "/student-resources/" },
    { id: 39, title: "Visit Us Page", description: "Content from Visit Us Page.", category: "Page", url: "/on-campus/visit-us/" },
    { id: 40, title: "Academic Calendar Page", description: "Content from Academic Calendar Page.", category: "Page", url: "/academic-calendar" },
    { id: 41, title: "Academic Programs Posts Page", description: "Content from Academic Programs Posts Page.", category: "Page", url: "/academic-programs-posts" },
    { id: 42, title: "All JIU News Page", description: "Content from All JIU News Page.", category: "Page", url: "/all-jiu-news" },
    { id: 43, title: "Campus Safety Page", description: "Content from Campus Safety Page.", category: "Page", url: "/campus-safety" },
    { id: 44, title: "Cards Data 1 Page", description: "Content from Cards Data 1 Page.", category: "Page", url: "/cards-data-1" },
    { id: 45, title: "Cards Data 2 Page", description: "Content from Cards Data 2 Page.", category: "Page", url: "/cards-data-2" },
    { id: 46, title: "Cards Data 3 Page", description: "Content from Cards Data 3 Page.", category: "Page", url: "/cards-data-3" },
    { id: 47, title: "Cards Data 4 Page", description: "Content from Cards Data 4 Page.", category: "Page", url: "/cards-data-4" },
    { id: 48, title: "Cards Data 5 Page", description: "Content from Cards Data 5 Page.", category: "Page", url: "/cards-data-5" },
    { id: 49, title: "Cards Data 6 Page", description: "Content from Cards Data 6 Page.", category: "Page", url: "/cards-data-6" },
    { id: 50, title: "Cards Data 7 Page", description: "Content from Cards Data 7 Page.", category: "Page", url: "/cards-data-7" },
    { id: 51, title: "Cards Data 8 Page", description: "Content from Cards Data 8 Page.", category: "Page", url: "/cards-data-8" },
    { id: 52, title: "Comunivation Page", description: "Content from Comunivation Page.", category: "Page", url: "/comunivation" },
    { id: 53, title: "Course Catalogs Page", description: "Content from Course Catalogs Page.", category: "Page", url: "/course-catalogs" },
    { id: 54, title: "Creatie Expression Page", description: "Content from Creatie Expression Page.", category: "Page", url: "/creatie-expression" },
    { id: 55, title: "Degree 1 Page", description: "Content from Degree 1 Page.", category: "Page", url: "/degree-1" },
    { id: 56, title: "Degree 2 Page", description: "Content from Degree 2 Page.", category: "Page", url: "/degree-2" },
    { id: 57, title: "Degree 3 Page", description: "Content from Degree 3 Page.", category: "Page", url: "/degree-3" },
    { id: 58, title: "Degree 4 Page", description: "Content from Degree 4 Page.", category: "Page", url: "/degree-4" },
    { id: 59, title: "Degree 5 Page", description: "Content from Degree 5 Page.", category: "Page", url: "/degree-5" },
    { id: 60, title: "Digital Media Page", description: "Content from Digital Media Page.", category: "Page", url: "/digital-media" },
    { id: 61, title: "Disability Page", description: "Content from Disability Page.", category: "Page", url: "/disability" },
    { id: 62, title: "Entertainment Media Page", description: "Content from Entertainment Media Page.", category: "Page", url: "/entertainment-media" },
    { id: 63, title: "Film Page", description: "Content from Film Page.", category: "Page", url: "/film" },
    { id: 64, title: "Headlines Posts Page", description: "Content from Headlines Posts Page.", category: "Page", url: "/headlines-posts" },
    { id: 65, title: "Human Behavior Page", description: "Content from Human Behavior Page.", category: "Page", url: "/human-behavior" },
    { id: 66, title: "Intrractive Media Page", description: "Content from Intrractive Media Page.", category: "Page", url: "/intrractive-media" },
    { id: 67, title: "Jade Times Conferences Page", description: "Content from Jade Times Conferences Page.", category: "Page", url: "/jade-times-conferences" },
    { id: 68, title: "Jade Times Journals Page", description: "Content from Jade Times Journals Page.", category: "Page", url: "/jade-times-journals" },
    { id: 69, title: "JIU Community Posts Page", description: "Content from JIU Community Posts Page.", category: "Page", url: "/jiu-community-posts" },
    { id: 70, title: "JIU PARTNERSHIPS POSTS Page", description: "Content from JIU PARTNERSHIPS POSTS Page.", category: "Page", url: "/jiu-partnerships-posts" },
    { id: 71, title: "JIU Speaker Event Article Page", description: "Content from JIU Speaker Event Article Page.", category: "Page", url: "/jiu-speaker-event-article" },
    { id: 72, title: "Job Positions Page", description: "Content from Job Positions Page.", category: "Page", url: "/job-positions" },
    { id: 73, title: "Journalism Page", description: "Content from Journalism Page.", category: "Page", url: "/journalism" },
    { id: 74, title: "Marketing Page", description: "Content from Marketing Page.", category: "Page", url: "/marketing" },
    { id: 75, title: "Media Arts Page", description: "Content from Media Arts Page.", category: "Page", url: "/media-arts" },
    { id: 76, title: "Performing Arts Page", description: "Content from Performing Arts Page.", category: "Page", url: "/performing-arts" },
    { id: 77, title: "Program Dates And Tuition Page", description: "Content from Program Dates And Tuition Page.", category: "Page", url: "/program-dates-and-tuition" },
    { id: 78, title: "Psychology Page", description: "Content from Psychology Page.", category: "Page", url: "/psychology" },
    { id: 79, title: "Student Highlights Posts Page", description: "Content from Student Highlights Posts Page.", category: "Page", url: "/student-highlights-posts" },
    { id: 80, title: "Technology Page", description: "Content from Technology Page.", category: "Page", url: "/technology" },
    { id: 81, title: "Terms Conditions Page", description: "Content from Terms Conditions Page.", category: "Page", url: "/terms-conditions" },
    { id: 82, title: "WorkShops Page", description: "Content from WorkShops Page.", category: "Page", url: "/workshops" }
];
