export const allPagesContent = [
    { id: 1, title: "Search Results Page", description: "Content from Search Results Page.", category: "Page", url: "/search" },
    { id: 2, title: "Events", description: "Content from Events page.", category: "Page", url: "/events/list/" },
    { id: 3, title: "Reviews Page", description: "Content from Reviews Page.", category: "Page", url: "/reviews/page/" },
    { id: 4, title: "About Page", description: "Content from About Page.", category: "Page", url: "/about" },
    { id: 5, title: "Accreditation Page", description: "Content from Accreditation Page.", category: "Page", url: "/Accreditation/" },
    { id: 6, title: "Admission Requirements Page", description: "Content from Admission Requirements Page.", category: "Page", url: "/admissions-requirements" },
    { id: 7, title: "Admissions Page", description: "Content from Admissions Page.", category: "Page", url: "/admissions" },
    { id: 8, title: "Affiliations Page", description: "Content from Affiliations Page.", category: "Page", url: "/affiliations/" },
    { id: 9, title: "Alumni", description: "Content from Alumni page.", category: "Page", url: "/alumni" },
    { id: 10, title: "Application Deadlines Page", description: "Content from Application Deadlines Page.", category: "Page", url: "/important-dates/" },
    { id: 11, title: "Apply JIU Page", description: "Content from Apply JIU Page.", category: "Page", url: "/apply-now/" },
    { id: 12, title: "Blog", description: "Content from Blog page.", category: "Page", url: "/blog/" },
    { id: 13, title: "Board Of Directors Page", description: "Content from Board Of Directors Page.", category: "Page", url: "/who-we-are/leadership/board-of-directors/" },
    { id: 14, title: "Cabinet Page", description: "Content from Cabinet Page.", category: "Page", url: "/cabinet/" },
    { id: 15, title: "Career And Alumni Services", description: "Content from Career And Alumni Services page.", category: "Page", url: "/career-and-alumni-services/" },
    { id: 16, title: "Contact Us", description: "Content from Contact Us page.", category: "Page", url: "/contact_us" },
    { id: 17, title: "Dates Tuition Page", description: "Content from Dates Tuition Page.", category: "Page", url: "/dates-tuition/" },
    { id: 18, title: "Degree Programs Page", description: "Content from Degree Programs Page.", category: "Page", url: "/Degree-Programs/" },
    { id: 19, title: "Faculty Directory Page", description: "Content from Faculty Directory Page.", category: "Page", url: "/faculty-directory/" },
    { id: 20, title: "Faq Page", description: "Content from Faq Page.", category: "Page", url: "/Faq" },
    { id: 21, title: "History Page", description: "Content from History Page.", category: "Page", url: "/JIU-history/" },
    { id: 22, title: "Home Page", description: "Content from Home Page.", category: "Page", url: "*" },
    { id: 23, title: "International Students Page", description: "Content from International Students Page.", category: "Page", url: "/admissions/international-students/" },
    { id: 24, title: "JIU News Page", description: "Content from JIU News Page.", category: "Page", url: "/JIU-in-the-news/" },
    { id: 25, title: "Jobs At JIU Page", description: "Content from Jobs At JIU Page.", category: "Page", url: "/jobs-at-nyfa/" },
    { id: 26, title: "Leadership At JIU Page", description: "Content from Leadership At JIU Page.", category: "Page", url: "/who-we-are/leadership/" },
    { id: 27, title: "Membership Page", description: "Content from Membership Page.", category: "Page", url: "/JIU-membership/" },
    { id: 28, title: "Military Dependent Students Page", description: "Content from Military Dependent Students Page.", category: "Page", url: "/admissions/veterans-military-dependent-students/" },
    { id: 29, title: "Mission And Purpose Page", description: "Content from Mission And Purpose Page.", category: "Page", url: "/mission-and-purpose/" },
    { id: 30, title: "NYFA Student Life Page", description: "Content from NYFA Student Life Page.", category: "Page", url: "/student-life/" },
    { id: 31, title: "Online Programes", description: "Content from Online Programes page.", category: "Page", url: "/online-programs/" },
    { id: 32, title: "President Page", description: "Content from President Page.", category: "Page", url: "/presidents-page/" },
    { id: 33, title: "Privacy Policy Page", description: "Content from Privacy Policy Page.", category: "Page", url: "/policy/" },
    { id: 34, title: "Programfinder Page", description: "Content from Programfinder Page.", category: "Page", url: "/programfinder/" },
    { id: 35, title: "Request Info Page", description: "Content from Request Info Page.", category: "Page", url: "/request-info/" },
    { id: 36, title: "Scholarship And Grants Page", description: "Content from Scholarship And Grants Page.", category: "Page", url: "/ScholarshipAndGrants_page/" },
    { id: 37, title: "Student Resource Page", description: "Content from Student Resource Page.", category: "Page", url: "/current-student-resources/" },
    { id: 38, title: "Student Resources", description: "Content from Student Resources page.", category: "Page", url: "/student-resources/" },
    { id: 39, title: "Visit Us Page", description: "Content from Visit Us Page.", category: "Page", url: "/on-campus/visit-us/" }
];